### ISSUE TITLE
大佬您这个工具是不是不支持中文

### ISSUE THREAD

**Issue by ccf200326** [ZQF-ReVN/RxGSD#3]
请问一下您，我在使用SPT_Parser.exe把json注回spt文件时显示RxCvt::ToMBCS Error!，检查了一下只要文件中有中文就会失败，日英不受影响，还有请问gsp编辑器要什么系统能运行

**Comment by ccf200326** [comment]
最近在试着拿您的工具来解包翻译他男3（之前老外也问了您的）

**Comment by Dir-A** [comment]
https://github.com/Dir-A/CMVS_Tools/issues/5#issuecomment-1968742895

**Comment by ccf200326** [comment]
谢谢大佬，还有我win10显示不能运行GSP_Editor.exe,是不是要别的版本的系统呢。

**Comment by Dir-A** [comment]
没日志，没截图，没答案
